### ISSUE TITLE
Side bar

### ISSUE THREAD

**Issue by paulvill** [paulvill/paulvill.github.io#25]
We need a side bar containing the various keys to interact with the data set.

For example the slider.

The site mockups can be found at the bottom of this issue

[issue #10 ](https://github.com/paulvill/paulvill.github.io/issues/10)

A first implementation of the side can be found [there](https://paulvill.github.io/layout_test/)

**Comment by 0xStarcat** [comment]
@paulvill Hey Paul! I'd like to pick this up

**Comment by paulvill** [comment]
Thanks you so much! @0xStarcat

**Comment by defenestrated** [comment]
thanks @0xStarcat! let me know if you need help interpreting the designs – we did them in a hurry so they're not so well marked-up

**Comment by 0xStarcat** [comment]
hey all @paulvill @defenestrated @chitech, I pushed up some code into my fork https://github.com/0xStarcat/paulvill.github.io for the sidebar. When I integrated into `layout_test`, however, it seems like I ran into a small problem. The `Materialize` library we are using for the pop-out legend from PR #26 overrides my styling to the point where my sidebar and `Materialize` can't really coexist nicely. I wanted to reach out to you all (and Christine in particular) for help with this. Can we incorporate the pop-out legend without the `Materialize` library?  

Because of how much custom CSS and detailing went into the sidebar, I don't think we can do the opposite and incorporate `Materialize` styles into the sidebar without redesigning the [mocks](https://github.com/paulvill/paulvill.github.io/files/1043046/eda_sitemocks-base.pdf) (which I suppose is option B).

I've also looked into seeing if we can have `Materialize` ignore a chunk of the HTML, but it seems like we can't selectively apply the library.

Also here's a screenshot of the sidebar w/o `materialize`

<img width="358" alt="screen shot 2017-06-03 at 11 15 35 am" src="https://cloud.githubusercontent.com/assets/17187192/26754744/80d64ec6-484e-11e7-84f9-7d5a66ad2824.png">

and with `materialize` overriding the styles

<img width="369" alt="screen shot 2017-06-03 at 11 15 47 am" src="https://cloud.githubusercontent.com/assets/17187192/26754749/8d58d588-484e-11e7-8dba-3fdd76c50bbf.png">

**Comment by paulvill** [comment]
Hey @0xStarcat !

Thanks a lot for sharing your progress! The screenshot looks really good. 

Indeed, @chitech or @defenestrated should be able to answer how to have it work with the `Materialize` library.

**Comment by chitech** [comment]
Hi Jeff @0xStarcat ,
Tomorrow, I will work a solution that doesn't use the Materialize library styles for the legend modal. As for the javascript, I will explore JQuery solution since I see that is already in use. Please let me know if you have any other questions.

**Comment by 0xStarcat** [comment]
Thanks Christine @chitech ! Please send me a note here when you've got it merged and I'll get to work on making a PR for the sidebar. A jQuery solution should be absolutely compatible with the Sidebar (I used pure CSS/HTML). Thanks for understanding and coming back to this =)

**Comment by chitech** [comment]
Hi Jeff @0xStarcat, 
I updated the code and removed the materialize library and replaced it with custom javascript and css styles. Just created a pull request on a branch called feature-legend.  Please let me know if you have questions.

**Comment by paulvill** [comment]
Thanks a lot for going back to your code @chitech ! I hope that it will work this time!

**Comment by 0xStarcat** [comment]
Thanks @chitech ! Sorry for the delay, I'll make a PR for the Sidebar then over the next day @paulvill .

**Comment by paulvill** [comment]
Ok great!!

**Comment by 0xStarcat** [comment]
I made a PR #31 for this issue. Please review! @paulvill @chitech @defenestrated 
Happy to make changes after review as well. Reach me here or for quicker response - email jeffahking@gmail.com

**Comment by paulvill** [comment]
Hi Jeff, @0xStarcat - thank you very much for your contribution! 
I will discuss with @defenestrated the best way to use the sidebar.
