### ISSUE TITLE
Displaying several modalities

### ISSUE THREAD

**Issue by paulvill** [paulvill/paulvill.github.io#7]
The various modalities of the datasets have to be visualized at the same time

Question 1: how to display several images at the same time such that all the layers can be visualized at the same time?

Question 2: how to choose a right colormap automatically so that the various layers can be interpreted at the same time?

**Comment by defenestrated** [comment]
@paulvill re: question 1, three thoughts:
1. perhaps we could figure out some variant of an "exploded view," using a stacked-paper metaphor for 2d views and scale-based transformations for 3d:
![image1](https://cloud.githubusercontent.com/assets/3525449/25502874/51f05a3e-2b66-11e7-9b87-03586b06975a.JPG)
or [here's a more traditional "exploded view"](https://www.google.com/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&cad=rja&uact=8&ved=0ahUKEwik77vsvMXTAhXHzVQKHdKlAAkQjRwIBw&url=http%3A%2F%2Fwww.voxshowroom.com%2Fus%2Fguitar%2Fultrasonic1.html&psig=AFQjCNFUKH27YRIsKS6RC78r8LNH_wKuuA&ust=1493411299816234)
2. there might be use here for [cross sectional representation](https://s-media-cache-ak0.pinimg.com/736x/da/28/65/da2865d23221ff3561d0c9a4a93e7215.jpg), especially if there's a way for things to animate in and out of the sectional and "gestalt" views, which brings me to:
3. generally, motion helps dramatically in perceptually understanding 3D objects – so it might be worth thinking about a kind of default rotation speed around an arbitrary axis, so that the spatial relationships between cells in various layers are immediately clear

**Comment by defenestrated** [comment]
re: question 2:
this, to me, seems like a more easily solved problem. we'll know before rendering what the maximum number of layers is, right? so couldn't we create a color scheme with a number of possibilities that corresponds to the total number of layers (even if most are "turned off")?
otherwise, i think you'd have to recalculate and change the colors of each visible layer every time a new one is added/removed – which would be also doable, but more complicated to think through and also perhaps confusing to the viewer...

**Comment by paulvill** [comment]
@defenestrated  I like good idea of the exploded view in 2D, and I think that we could directly use parts of the code from [this example](https://threejs.org/examples/webgl_geometry_shapes.html) . 

Also, for this to work well, we will need to have a transparent background instead of black, for the images showing only a unique modality.

As for the question of colors, we indeed know the number of layers, at least at the time of upload. There are some ideas here on [how to best choose the colors](http://tools.medialab.sciences-po.fr/iwanthue/), it is a link that Anne shared with us some time ago. They use the [chroma.js](http://gka.github.io/chroma.js/) which seems very nice.

**Comment by defenestrated** [comment]
yeah that iwanthue is interesting, and chroma.js looks great. we should definitely build on those!

i think the exploded view could work in 3d too, actually, if we think in terms of "normal" vectors – in this case it'd probably just be away from a centroid that we calculate, but still – given that users will be able to move around, in combination with color differences, i think the perceptual issues with rendering depth won't be so bad.

something like this...
![explode-1x](https://cloud.githubusercontent.com/assets/3525449/25631200/a81e723a-2f3d-11e7-9bd5-0c154edea04d.jpg)

**Comment by paulvill** [comment]
For the colors, there is a really nice animation at this [address](https://www.vis4.net/blog/posts/avoid-equidistant-hsv-colors/) showing how the CIE L*a*b* color space can be used to generate sets of colors for a given perceived brightness (Luminance, L). The intensity of the chemical signal (which is measured, at a given spatial position, as changes in concentration of some fluorophore) could be encoded as a change in perceived brightness, whereas the various signals (specific molecules which have been excited) could be encoded as changes in hue. When superimposing several signals at the same time, we might then have to order them in increasing brightness order with brightest on top.

For the exploded view, I agree that it is interesting for 3D as well, the main limitation comes from the fact that the 3D datasets come as 3D stacks of voxels (each with some rgb value). To be able to show layers in 3D, we would have to first extract surfaces where the interesting signal lie, before being able to visualize them at various distances of the centroid.

You could be interested to look at this [paper](http://www.nature.com/nmeth/journal/v12/n12/full/nmeth.3648.html) by Idse Heemskerk and Sebastian Streichan at the Kavli Institute for Theoretical Physics in Santa Barbara. They show a way to map 3D tissues in developing to 2D images, using Mercator projection (or equivalent). They also maintain a website (http://tissuecartography.org/).

**Comment by defenestrated** [comment]
Reducing the dimensions à la that paper is an interesting idea – it would present all the problems of a cartographic endeavor, but I wonder if some kind of surface mapping would be useful as a navigational tool...

Re: the 3D datasets, you're saying they come in as fully packed boxes of voxels, rather than a set of only the relevant points (visible fluorophore)? That does make it more complicated. Is that the way it works because there are trace amounts of the fluorophore dye in (potentially) every single voxel? From my ignorant vantage point, it seems like that would _radically_ increase the processing load, whereas if you ignored all the voxels under a certain brightness threshhold, you'd then be left with point clouds for which you could compute a centroid close enough at least to project them at a distance away.

Also, from my understanding of the processes at work here, a surface wouldn't really cut it, right? Seems to me the whole _point_ is that cells are moving around in 3D, passing between any surfaces we'd be imposing.

For me, the most intuitive way of understanding complex spatially-nested objects is by repeatedly toggling layers (or individual objects) on and off, and slowly building a sense of the gestalt environment. Perhaps, then, exploded and cross-section views aren't the right direction, and we should instead focus on intuitive (=fast) ways of manipulating layer opacity?

**Comment by paulvill** [comment]
There is also some decent amount of manual tuning of parameters to have their algorithm work, I don't think that it is possible to have it as an automatically processed step for now.

For the 3D datasets, this is exactly it. The embryos we are looking at, are usually made of folded tissues, but the signal can be anywhere in the 3d space. So maybe we can think of a visualization with a cursor to change a threshold depending on pixel intensit/layer opacity.  There is a nice example of how that could look like [here](http://www.allencell.org/3d-cell-viewer.html). 

I think if we can indeed then include a scaling factor depending on the channel we are looking at, that might really help understand the 3D structure.

**Comment by paulvill** [comment]
Blending in three.js - examples are [here](https://threejs.org/examples/webgl_materials_blending.html)

Color a grayscale image in javascript [there](https://css-tricks.com/color-filters-can-turn-your-gray-skies-blue/)

**Comment by defenestrated** [comment]
to do it on the material directly: [threejs doc](https://threejs.org/examples/#webgl_materials_blending_custom)
